drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table adresse cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK8c7m0cp2tls68sgnb8lydwiga;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table adresse cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
